/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Scooter = {
  _id: string;
  _type: "scooter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  year?: number;
  color?: string;
  cc?: number;
  priceDaily?: number;
  priceMonthly?: number;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  note?: LocaleString;
  available?: boolean;
  order?: number;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  fr?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  country?: string;
  service?: "dtv" | "training" | "general";
  content?: LocaleText;
  rating?: number;
  featured?: boolean;
};

export type LocaleText = {
  _type: "localeText";
  en?: string;
  fr?: string;
};

export type TrainingSchedule = {
  _id: string;
  _type: "trainingSchedule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  day?: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
  timeSlots?: Array<{
    start?: string;
    end?: string;
    label?: LocaleString;
    _type: "timeSlot";
    _key: string;
  }>;
  level?: "all" | "beginner" | "kids" | "fighter" | "women";
  notes?: LocaleText;
  order?: number;
};

export type Fighter = {
  _id: string;
  _type: "fighter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  fightName?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  countryCode?: string;
  year?: number;
  fights?: number;
  venues?: Array<string>;
  quote?: LocaleString;
  achievements?: Array<string>;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Coach = {
  _id: string;
  _type: "coach";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  role?: LocaleString;
  bio?: LocaleText;
  featured?: boolean;
  order?: number;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: BlogPostReference;
  language?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
  publishedAt?: string;
  category?: CategoryReference;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  slug?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Scooter
  | LocaleString
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | LocaleText
  | TrainingSchedule
  | Fighter
  | Slug
  | Coach
  | TranslationMetadata
  | InternationalizedArrayReference
  | BlogPostReference
  | InternationalizedArrayReferenceValue
  | CategoryReference
  | BlogPost
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/queries.ts
// Variable: COACHES_QUERY
// Query: *[_type == "coach"] | order(order asc) {    _id, name, slug, photo, role, bio, featured, order  }
export type COACHES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  role: LocaleString | null;
  bio: LocaleText | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: src/lib/queries.ts
// Variable: FEATURED_FIGHTERS_QUERY
// Query: *[_type == "fighter" && featured == true] | order(year desc, name asc) {    _id, name, slug, photo, fightName, countryCode, year, fights, venues, quote, achievements  }
export type FEATURED_FIGHTERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  fightName: string | null;
  countryCode: string | null;
  year: number | null;
  fights: number | null;
  venues: Array<string> | null;
  quote: LocaleString | null;
  achievements: Array<string> | null;
}>;

// Source: src/lib/queries.ts
// Variable: FIGHTERS_QUERY
// Query: *[_type == "fighter"] | order(year desc, name asc) {    _id, name, slug, photo, fightName, countryCode, year, fights, venues, quote, achievements, featured  }
export type FIGHTERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  fightName: string | null;
  countryCode: string | null;
  year: number | null;
  fights: number | null;
  venues: Array<string> | null;
  quote: LocaleString | null;
  achievements: Array<string> | null;
  featured: boolean | null;
}>;

// Source: src/lib/queries.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true && ($service == null || service == $service)] {    _id, name, country, service, content, rating  }
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  country: string | null;
  service: "dtv" | "general" | "training" | null;
  content: LocaleText | null;
  rating: number | null;
}>;

// Source: src/lib/queries.ts
// Variable: SCHEDULE_QUERY
// Query: *[_type == "trainingSchedule"] | order(order asc) {    _id, day, timeSlots, level, notes, order  }
export type SCHEDULE_QUERY_RESULT = Array<{
  _id: string;
  day: "fri" | "mon" | "sat" | "sun" | "thu" | "tue" | "wed" | null;
  timeSlots: Array<{
    start?: string;
    end?: string;
    label?: LocaleString;
    _type: "timeSlot";
    _key: string;
  }> | null;
  level: "all" | "beginner" | "fighter" | "kids" | "women" | null;
  notes: LocaleText | null;
  order: number | null;
}>;

// Source: src/lib/queries.ts
// Variable: BLOG_POSTS_BY_LANG_QUERY
// Query: *[_type == "blogPost" && language == $lang && defined(publishedAt)] | order(publishedAt desc) {    _id, title, slug, mainImage, seoDescription, publishedAt,    category->{ _id, name, slug }  }
export type BLOG_POSTS_BY_LANG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  seoDescription: string | null;
  publishedAt: string | null;
  category: {
    _id: string;
    name: LocaleString | null;
    slug: Slug | null;
  } | null;
}>;

// Source: src/lib/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug && language == $lang][0] {    _id, title, language, slug, mainImage, content,    seoTitle, seoDescription, publishedAt,    category->{ _id, name, slug },    "translations": *[_type == "translation.metadata" && references(^._id)].translations[].value->{      language, slug    }  }
export type BLOG_POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  language: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  publishedAt: string | null;
  category: {
    _id: string;
    name: LocaleString | null;
    slug: Slug | null;
  } | null;
  translations: Array<{
    language: string | null;
    slug: Slug | null;
  } | null>;
} | null;

// Source: src/lib/queries.ts
// Variable: SCOOTERS_QUERY
// Query: *[_type == "scooter"] | order(order asc, name asc) {    _id, name, year, color, cc, priceDaily, priceMonthly, photo, note, available  }
export type SCOOTERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  year: number | null;
  color: string | null;
  cc: number | null;
  priceDaily: number | null;
  priceMonthly: number | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  note: LocaleString | null;
  available: boolean | null;
}>;

// Source: src/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(name.en asc) {    _id, name, slug  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: LocaleString | null;
  slug: Slug | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "coach"] | order(order asc) {\n    _id, name, slug, photo, role, bio, featured, order\n  }\n': COACHES_QUERY_RESULT;
    '\n  *[_type == "fighter" && featured == true] | order(year desc, name asc) {\n    _id, name, slug, photo, fightName, countryCode, year, fights, venues, quote, achievements\n  }\n': FEATURED_FIGHTERS_QUERY_RESULT;
    '\n  *[_type == "fighter"] | order(year desc, name asc) {\n    _id, name, slug, photo, fightName, countryCode, year, fights, venues, quote, achievements, featured\n  }\n': FIGHTERS_QUERY_RESULT;
    '\n  *[_type == "testimonial" && featured == true && ($service == null || service == $service)] {\n    _id, name, country, service, content, rating\n  }\n': FEATURED_TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "trainingSchedule"] | order(order asc) {\n    _id, day, timeSlots, level, notes, order\n  }\n': SCHEDULE_QUERY_RESULT;
    '\n  *[_type == "blogPost" && language == $lang && defined(publishedAt)] | order(publishedAt desc) {\n    _id, title, slug, mainImage, seoDescription, publishedAt,\n    category->{ _id, name, slug }\n  }\n': BLOG_POSTS_BY_LANG_QUERY_RESULT;
    '\n  *[_type == "blogPost" && slug.current == $slug && language == $lang][0] {\n    _id, title, language, slug, mainImage, content,\n    seoTitle, seoDescription, publishedAt,\n    category->{ _id, name, slug },\n    "translations": *[_type == "translation.metadata" && references(^._id)].translations[].value->{\n      language, slug\n    }\n  }\n': BLOG_POST_QUERY_RESULT;
    '\n  *[_type == "scooter"] | order(order asc, name asc) {\n    _id, name, year, color, cc, priceDaily, priceMonthly, photo, note, available\n  }\n': SCOOTERS_QUERY_RESULT;
    '\n  *[_type == "category"] | order(name.en asc) {\n    _id, name, slug\n  }\n': CATEGORIES_QUERY_RESULT;
  }
}
